### ISSUE TITLE
DASWG: Leave System WakeLock API in WICG until there is a second implementer

### ISSUE THREAD

**Issue by tantek** [w3c/das-charter#101]
Per [DAS charter feedback](https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0012.html): We believe it would be prudent for the System WakeLock API to go through the WICG process until it gets implementation commitment from at least a second browser vendor.

Having said that, we would be comfortable with having WICG incubated specs being explicitly listed as charter as work items the working group could adopt at a future date. However, we'd like to see them listed in a manner similar to the [Web Apps WG Charter's section on WICG Specs](https://www.w3.org/2019/05/webapps-charter.html#wicgspecs) (i.e., separated out of the main deliverables list for the working group).

cc: [@dwsinger](https://github.com/dwsinger) [@pes10k](https://github.com/pes10k) [@marcoscaceres](https://github.com/marcoscaceres)

(Originally published at: https://tantek.com/2020/188/b4/das-system-wakelock-api-wicg)

**Comment by anssiko** [comment]
The System Wake Lock API has been worked on in the DAS WG as part of the Wake Lock API [since 2015](https://www.w3.org/TR/2015/WD-wake-lock-20150212/). It has never been a WICG deliverable, so the title of this issue is misleading ("Leave System WakeLock API in WICG").

The DAS WG recorded a consensus [1] to split the Wake Lock API into two separate DAS WG deliverables in Feb 2020:

>The rationale for the split is to allow the screen wake lock subset of the spec that has strong use cases, implementation experience, and web developer support to advance along the W3C Rec Track on its own merits, while allow the system wake lock to be further developed in parallel before its advancement.

That CfC passed with no concerns and no new information has been brought to the group's attention that would support the objector's proposal.

Also, we feel the objector fails to clearly articulate the value of reversing to WICG, especially considering the expertise for this problem space has been in the DAS WG since 2015 with many of the W3C member organizations committed to the DAS WG and this deliverable.

The DAS WG believes moving this work off of the standards track would be considered harmful.

[1] https://lists.w3.org/Archives/Public/public-device-apis/2020Feb/0011.html

**Comment by samuelweiler** [comment]
@tantek. Any response to the above?  Based on the history, by itself (at least as told by Anssi), I would be inclined to leave this in the WG.

**Comment by xfq** [comment]
The Director [has approved](https://www.w3.org/2020/11/das-wg-charter.html) the Devices and Sensors Working Group charter, taking into consideration the input from an experiment conducted by the Advisory Board and the TAG and decided that a chartered Working Group was best suited to address these concerns. These concerns will not be ignored but the discussion should be moved into the individual specification issue tracker where the concerns can be addressed.

See https://lists.w3.org/Archives/Member/w3c-ac-members/2020OctDec/0034.html (member-only link) for the Director's decision.
