### ISSUE TITLE
Generic-sensor based geolocation API?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/das-charter#32]
Should the group's scope include a revisited Geolocation API based on the Generic Sensor Framework? Should there be some incubated proposal before considering it?

**Comment by anssiko** [comment]
Here's the Geolocation Sensor proposal:

https://wicg.github.io/geolocation-sensor/

@dontcallmedom, even if we were to incubate this spec in WICG, I'd prefer to have the spec live under the `w3c` GH org rather than `wicg` to not need to move the issues around after assumed transition to the DAS WG by the end of the year. Would that be fine? Last time I checked moving issues with all their associated metadata was impossible when migrating repos.

**Comment by xfq** [comment]
@anssiko

Is https://help.github.com/articles/about-repository-transfers/ enough? Or maybe we can find out how specs like IntersectionObserver were moved.

**Comment by anssiko** [comment]
@xfq, thanks! It seems GitHub has improved its repo transfer process. Given this, I'd be fine hosting this repo under wicg during incubation.

**Comment by anssiko** [comment]
I just proposed the Geolocation Sensor to WICG:

https://discourse.wicg.io/t/proposal-geolocation-sensor-based-on-the-generic-sensor-api/2355
