### ISSUE TITLE
Extensible charter?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/das-charter#5]
Should we phrase our charter so that any API that matches our scope can be added without rechartering? If so, what's the right wording?

**Comment by wayneca** [comment]
From the W3C Patent Policy: "As a condition of participating in a Working Group, each participant (W3C Members, W3C Team members, invited experts, and members of the public) shall agree to make available under W3C RF licensing requirements any Essential Claims related to the work of that particular Working Group."  Unlike Community Groups, it's licensing the whole spec, not just one's own contributions.  That makes Charter scope and deliverables important because it lets you know when you join the WG generally what it is that you may have to license.  

From the proposed charter: "The scope of this Working Group is this creation of API specifications for a device’s services that can be exposed to Web applications . Devices in this context include desktop computers, laptop computers, mobile Internet devices (MIDs), cellular phones, TVs, cameras and other connected devices."  Without a list of deliverables to narrow that, specs could be about just about anything.  That could force Members to monitor and quit the WG if the WG begins work on a spec they don't want to license.  Putting deliverables in Charters has that debate at charter creation time and work can be put in its own WG if it would impact whether Members would approve the WG.  

Rechartering to add a deliverable shouldn't be that big a deal.  But, it gives the Advisory Committee (the Membership's representatives) the chance to consider the addition.

So, deliverables should stay in the charter and just describe the things the WG wants to be able to work on.

**Comment by dontcallmedom** [comment]
@wcarr I understand we should avoid a completely open-ended charter, but I'll also note that some WGs have adopted much more open charters (e.g. the CSS WG)

One possible option I was wondering was whether we could explore and experiment with a lightweight process for adding specs to the list of in-scope deliverables; I had drafted a rough proposal which would use a shortened and focused set of reviews (by W3C management and AC).

I'd be interested in hearing if this is something you think is worth exploring or if you prefer we stick with existing processes.

**Comment by wayneca** [comment]
I considered objecting to the CSS charter, but CSS just isn't scary.  It's pretty clear what it's about.  Random APIs can be scarier for people worried about having to license patents without knowing what types of things they could be about.

We could already have a lightweight process with the existing rules, if the AC and Director both agreed to just look at the impact of the specific changes in deliverables if that is all that changed.  So, not redabate other issues about the WG as long as the duration wasn't being extended.

**Comment by dontcallmedom** [comment]
Restricting the Director/AC review of changes to those specifically in the deliverables list was roughly my idea of the lightweight process; I think we could enforce such a restriction by documenting it in the charter.

**Comment by wayneca** [comment]
The Charter can say something like: "If additional deliverables need to be added to the Charter before the Charter expires, the WG will prepare an updated Charter that differs only in deliverables.  In the interest of agile spec development, the WG requests that the Advisory Committee and Director restrict approval reviews for those Charter deliverables adjustments to  just the changes in the Charter, rather than considering the entire Charter again for review.  In the past, it has taken too long for simple deliverables changes. "

But, that doesn't guarantee it - a Charter can't override the W3C Process.  I think it's still worth saying and that it may set a good precedent.
