### ISSUE TITLE
Mention a11y?

### ISSUE THREAD

**Issue by xfq** [w3c/das-charter#70]
In §2.1 Success Criteria:

> Each specification must contain a section detailing any known security or privacy implications for implementers, Web authors, and end users.

In the AC review, @LJWatson and @Ryladog mentioned that accessibility could be included, along with privacy and security.

**Comment by xfq** [comment]
Note that we already mention accessibility in §4.1 currently:

> For all specifications, this Working Group will seek horizontal review for accessibility, internationalization, performance, privacy, and security with the relevant Working and Interest Groups, and with the TAG.

**Comment by LJWatson** [comment]
Thanks for raising this @XFQ.


There is a difference between the horizontal review, and including a section in a spec that contains accessibility information for implementors, authors, and consumers.:
* The horizontal review will help make sure that what is in the spec is accessible, and does not cause any accessibility issues (in the same way that the horizontal reviews for privacy and security will do for their respective subject areas)
* The accessibility section in the spec will inform implementors and authors about the things they should consider when using the spec (the same as the privacy and security sections do for their respective subject areas)

So both things are needed, in order to make sure the spec itself has accessibility as a core design principle (along with security and privacy), and that implementors and authors are aware of any accessibility considerations when using it.

**Comment by samuelweiler** [comment]
This requirement was already present, but it was two paragraphs later:

> Where applicable, each specification should contain a section on accessibility that describes the benefits and impacts, including ways specification features can be used to address them, and recommendations for maximising accessibility in implementations.

https://github.com/w3c/dap-charter/pull/71  reorders section 2.1 to make this more obvious
