### ISSUE TITLE
Mention Web of Things WG in Coordination

### ISSUE THREAD

**Issue by xfq** [w3c/das-charter#93]
The scope of DAS WG is to develop browser APIs, and WoT people are also getting interested in Web browsers (including embedded browsers and usual Web browsers to provide user interface for IoT services). Since the [updated WoT WG charter](https://www.w3.org/2020/01/wot-wg-charter.html#w3c-coordination) also includes DAS WG within the Coordination section, I suggest that we mention WoT in the Coordination section as well.

**Comment by anssiko** [comment]
My preference would be to limit liaisons stated in the charter to groups we have, or will have, an active interaction with, either through normative dependency, or other similar strong connection such as shared commitment to privacy-focused web features and APIs. Maintaining liaisons requires effort, and I'd prefer not to overcommit the group. If we can identify a champion who volunteers to act as a bridge between the DAS and WoT groups I'm happy to reconsider my position.

We can certainly coordinate with WoT WG and other groups on an ad-hoc basis even if there's no explicit mention in the charter. WoT WG has had the DAS WG as one of its many liaisons [since 2016](https://www.w3.org/2016/12/wot-wg-2016.html).

**Comment by anssiko** [comment]
Discussed with @zolkis from WoT WG who has been looking at the Generic Sensor API in the context of the WoT and we concluded an informal liaison (that has been ongoing for the last 4 years thanks to shared participants) is adequate, and no charter edits needed to formalize this relationship at this time.

**Comment by plehegar** [comment]
unless there is a strong reason not to list the WoT WG, which would worry me, I suggest listing the liaison. If it doesn't get used, no harm done.

**Comment by anssiko** [comment]
It's all about focus as explained earlier.

I also worry a little we'd discriminate other groups not listed with whom DAS WG has similar liaison relationship i.e. no normative dependency, but some shared interest.

**Comment by plehegar** [comment]
Having a liaison doesn't mean that you need to loose the focus. At the minimum, the Director will ask if you got reviews from the WoT WG at your transition time, and will not block if the WoT WG declined to give such review. It doesn't change the scope of the DAS WG and doesn't force the Group to take on new use cases. The effort added is minimal.

**Comment by anssiko** [comment]
I infer W3M wants to see this liaison in the charter. I trust your judgment. PRs welcome.

**Comment by plehegar** [comment]
Having a liaison doesn't mean that you need to loose the focus. At the minimum, the Director will ask if you got reviews from the WoT WG at your transition time, and will not block if the WoT WG declined to give such review. It doesn't change the scope of the DAS WG and doesn't force the Group to take on new use cases. The effort added is minimal (and the upcoming tooling, it will be as cheap as we can make it to ask for reviews)

**Comment by ashimura** [comment]
Thank you very much, @anssiko @xfq and @plehegar !
